In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

kilocalories_data = pd.read_csv('data_kilocalories.csv')
kilocalories_data.head()

food_name  proteins   fats  carbohydrates  kilocalories type_of_food
0     bacon     33.92  35.09            1.7         468.0         meat
1      beef     20.20   2.80           75.9         106.0         meat
2   chicken     18.20  18.40            0.0         238.0         meat
3      duck     18.99  28.35            0.0         337.0         meat
4       ham     22.60  20.90            0.0         279.0         meat

In [16]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(kilocalories_data, 
                                         test_size=0.2,
                                         random_state=42)

In [29]:
train_data

food_name  proteins    fats  carbohydrates  kilocalories   
13    broccoli      3.30   0.200           5.70          43.0  \
33       grain     11.50   1.300          67.90         329.0   
34      lentil     24.63   1.060          52.65         352.0   
3         duck     18.99  28.350           0.00         337.0   
17       onion      1.40   0.200           8.20          41.0   
54       juice      0.41   0.008          12.00          51.0   
8     sardines     17.90  19.700           0.00         249.0   
6      sausage     11.00  23.900           0.40         261.0   
31  watermelon      0.70   0.100           5.80          27.0   
4          ham     22.60  20.900           0.00         279.0   
45      yogurt      4.10   1.500           5.90          57.0   
19   pea_grain     20.00   2.000          67.00         360.0   
52      waffle      8.00  14.000          33.00         291.0   
36       wheat     13.00   2.500          57.50         304.0   
53      coffee     13.90  14.400           4.10         200.6   
41   ice_cream      3.70  15.000          20.40         232.0   
58      tomato      1.10   0.200           3.80          24.0   
15      carrot      0.93   0.240           6.78          41.0   
40        eggs     12.70  11.500           0.70         157.0   
27       melon      0.60   0.300           7.40          35.0   
26       lemon      0.90   0.100           3.00          34.0   
24      cherry      0.80   0.200          10.60          52.0   
44  sour_cream      2.50  20.000           3.40         206.0   
11     avocado      2.00  20.000           7.40         200.0   
32   buckwheat     12.60   3.300          57.10         308.0   
55    lemonade      0.00   0.000          11.50          45.0   
43        milk      2.90   2.500           4.80          54.0   
37      butter      0.80  72.500           1.30         661.0   
29      orange      0.90   0.200           8.10          43.0   
46     biscuit      7.50   9.800          74.40         417.0   
1         beef     20.20   2.800          75.90         106.0   
21      almond     22.00  51.000          20.00         578.0   
2      chicken     18.20  18.400           0.00         238.0   
49        twix      4.10  24.200          64.80         497.0   
39       cream      4.00  15.000          19.00         226.0   
35      barley     10.30   2.400          56.40         288.0   
23  blackberry      1.50   0.500           4.40          34.0   
60      cutlet     14.10  15.700           6.60         222.5   
10       trout     19.10   3.500           0.00         142.0   
22      banana      1.50   0.500          21.00          96.0   
18   pea_fresh      5.00   0.200           8.30          81.0   
61       pizza      9.70  25.700          12.90         321.6   
20      potato      2.00   0.400          16.30          77.0   
7          cod     16.00   0.600           0.00          69.0   
42       kefir      2.90   3.200           4.00          59.0   
14     cabbage      1.80   0.100           4.70          28.0   
28        lime      0.70   0.200           7.74          30.0   
51       honey      0.80  80.000           1.20         328.0   
38      cheese     23.20  29.500           0.00         364.0   

         type_of_food  
13    fruit_vegetable  
33        grains_nuts  
34        grains_nuts  
3                meat  
17    fruit_vegetable  
54              drunk  
8                meat  
6                meat  
31    fruit_vegetable  
4                meat  
45              dairy  
19        grains_nuts  
52  bakery_and_sweets  
36        grains_nuts  
53              drunk  
41              dairy  
58    fruit_vegetable  
15    fruit_vegetable  
40               meat  
27    fruit_vegetable  
26    fruit_vegetable  
24    fruit_vegetable  
44              dairy  
11    fruit_vegetable  
32        grains_nuts  
55              drunk  
43              dairy  
37              dairy  
29    fruit_vegetable  
46  bakery_and_sweets  
1         

In [26]:
X1_train = train_data['proteins'].to_numpy()
X2_train = train_data['fats'].to_numpy()
X3_train = train_data['carbohydrates'].to_numpy()
y_train = train_data['kilocalories'].to_numpy()

X1_test = test_data['proteins'].to_numpy()
X2_test = test_data['fats'].to_numpy()
X3_test = test_data['carbohydrates'].to_numpy()
y_test = test_data['kilocalories'].to_numpy()

X1_train

array([ 3.3 , 11.5 , 24.63, 18.99,  1.4 ,  0.41, 17.9 , 11.  ,  0.7 ,
       22.6 ,  4.1 , 20.  ,  8.  , 13.  , 13.9 ,  3.7 ,  1.1 ,  0.93,
       12.7 ,  0.6 ,  0.9 ,  0.8 ,  2.5 ,  2.  , 12.6 ,  0.  ,  2.9 ,
        0.8 ,  0.9 ,  7.5 , 20.2 , 22.  , 18.2 ,  4.1 ,  4.  , 10.3 ,
        1.5 , 14.1 , 19.1 ,  1.5 ,  5.  ,  9.7 ,  2.  , 16.  ,  2.9 ,
        1.8 ,  0.7 ,  0.8 , 23.2 ])

In [28]:
X1_train = X1_train.reshape((49,1))
X2_train = X2_train.reshape((49,1))
X3_train = X3_train.reshape((49,1))
print(X1_train, X2_train, X3_train)

X_train = np.column_stack((X1_train, X2_train, X3_train))
X_train

[[ 3.3 ]
 [11.5 ]
 [24.63]
 [18.99]
 [ 1.4 ]
 [ 0.41]
 [17.9 ]
 [11.  ]
 [ 0.7 ]
 [22.6 ]
 [ 4.1 ]
 [20.  ]
 [ 8.  ]
 [13.  ]
 [13.9 ]
 [ 3.7 ]
 [ 1.1 ]
 [ 0.93]
 [12.7 ]
 [ 0.6 ]
 [ 0.9 ]
 [ 0.8 ]
 [ 2.5 ]
 [ 2.  ]
 [12.6 ]
 [ 0.  ]
 [ 2.9 ]
 [ 0.8 ]
 [ 0.9 ]
 [ 7.5 ]
 [20.2 ]
 [22.  ]
 [18.2 ]
 [ 4.1 ]
 [ 4.  ]
 [10.3 ]
 [ 1.5 ]
 [14.1 ]
 [19.1 ]
 [ 1.5 ]
 [ 5.  ]
 [ 9.7 ]
 [ 2.  ]
 [16.  ]
 [ 2.9 ]
 [ 1.8 ]
 [ 0.7 ]
 [ 0.8 ]
 [23.2 ]] [[2.000e-01]
 [1.300e+00]
 [1.060e+00]
 [2.835e+01]
 [2.000e-01]
 [8.000e-03]
 [1.970e+01]
 [2.390e+01]
 [1.000e-01]
 [2.090e+01]
 [1.500e+00]
 [2.000e+00]
 [1.400e+01]
 [2.500e+00]
 [1.440e+01]
 [1.500e+01]
 [2.000e-01]
 [2.400e-01]
 [1.150e+01]
 [3.000e-01]
 [1.000e-01]
 [2.000e-01]
 [2.000e+01]
 [2.000e+01]
 [3.300e+00]
 [0.000e+00]
 [2.500e+00]
 [7.250e+01]
 [2.000e-01]
 [9.800e+00]
 [2.800e+00]
 [5.100e+01]
 [1.840e+01]
 [2.420e+01]
 [1.500e+01]
 [2.400e+00]
 [5.000e-01]
 [1.570e+01]
 [3.500e+00]
 [5.000e-01]
 [2.000e-01]
 [2.570e+01]
 [4.000e-01]

array([[3.300e+00, 2.000e-01, 5.700e+00],
       [1.150e+01, 1.300e+00, 6.790e+01],
       [2.463e+01, 1.060e+00, 5.265e+01],
       [1.899e+01, 2.835e+01, 0.000e+00],
       [1.400e+00, 2.000e-01, 8.200e+00],
       [4.100e-01, 8.000e-03, 1.200e+01],
       [1.790e+01, 1.970e+01, 0.000e+00],
       [1.100e+01, 2.390e+01, 4.000e-01],
       [7.000e-01, 1.000e-01, 5.800e+00],
       [2.260e+01, 2.090e+01, 0.000e+00],
       [4.100e+00, 1.500e+00, 5.900e+00],
       [2.000e+01, 2.000e+00, 6.700e+01],
       [8.000e+00, 1.400e+01, 3.300e+01],
       [1.300e+01, 2.500e+00, 5.750e+01],
       [1.390e+01, 1.440e+01, 4.100e+00],
       [3.700e+00, 1.500e+01, 2.040e+01],
       [1.100e+00, 2.000e-01, 3.800e+00],
       [9.300e-01, 2.400e-01, 6.780e+00],
       [1.270e+01, 1.150e+01, 7.000e-01],
       [6.000e-01, 3.000e-01, 7.400e+00],
       [9.000e-01, 1.000e-01, 3.000e+00],
       [8.000e-01, 2.000e-01, 1.060e+01],
       [2.500e+00, 2.000e+01, 3.400e+00],
       [2.000e+00, 2.000e+01, 7.40

In [30]:
from sklearn.linear_model import LinearRegression

# создается объект модели:
model = LinearRegression()       
# обучение модели на тренировочных данных:
model.fit(X_train, y_train)

LinearRegression()

In [31]:
X1_test = X1_test.reshape((len(X1_test),1))
X2_test = X2_test.reshape((len(X2_test),1))
X3_test = X3_test.reshape((len(X3_test),1))

X_test = np.column_stack((X1_test, X2_test, X3_test))

In [32]:
y_test_predicted = model.predict(X_test)

# напечатаем результат в виде таблицы
header = f"X_test\ty_test\ty_test_predicted"
print(header, '\n', '-'*len(header), sep='')
for i in range(len(y_test)):
    print(f"{X_test[i]}\t{y_test[i]}\t{int(y_test_predicted[i])}")

X_test	y_test	y_test_predicted
------------------------------
[ 7.2 17.5 38.5]	340.8	296
[0. 0. 0.]	1.0	18
[33.92 35.09  1.7 ]	468.0	435
[ 8.85  3.33 46.72]	266.0	233
[19.4  7.1  0. ]	142.0	165
[ 8.  25.6 56. ]	500.0	410
[0.8 0.1 2.5]	14.0	30
[26.12  1.53 33.29]	341.0	267
[0.7 0.2 6.5]	35.0	43
[17.   5.   1.8]	120.0	144
[0.79 0.37 6.16]	34.0	44
[18.2  3.3  0. ]	103.0	133
[ 4.7 14.9 36.1]	294.0	257


In [33]:
from sklearn.metrics import mean_squared_error as mse

y_train_predicted = model.predict(X_train)

train_rmse = mse(y_train, y_train_predicted, squared=False)
test_rmse = mse(y_test, y_test_predicted, squared=False)

print(f'{train_rmse = }, {test_rmse = }')

train_rmse = 60.71355408142439, test_rmse = 40.867394994867716


In [34]:
a = model.intercept_
b = model.coef_
print(f'{a = }, {b = }')

a = 18.320612098183602, b = array([5.09458854, 6.81679728, 3.1612737 ])


In [35]:
def gg(x1,x2,x3):
    return x1*b[0] + x2*b[1] + x3*b[2] + a
print(gg(23.6,1.9,0.4))

152.7693258930539


In [38]:
print(gg(4.3,14.5,25.8))

220.63176486774694
